---
title: "R Notebook"
output: html_notebook
---

# Exploratory Data Analaysis

Libraries

```{r}
library(tidyverse)
library(rvest)
library(gender)
```

## Scraping part

```{r}
# This data was the least complicated to scrape so I scraped it, the other stats I ended up pulling from this github: https://github.com/komaksym/UFC-DataLab
base_url = "http://www.ufcstats.com/statistics/fighters?page=all&char="

url_list = map(letters, ~ paste0(base_url,.x))


# This should map all the data to rows
# Make sure to remove NA's from the dataset
scrape_player_stats = function(urls) {
  map_dfr(urls, function(url) {
    Sys.sleep(sample(1:5, 1))
    
    player_stats = read_html(url) %>%
      html_element('table') %>%
      html_table()
  })
}


# You want to perform a decent NA removal. I'd say remove only when the first name is NA
# player_stats = scrape_player_stats(url_list)

# From here you will likely want to filter the data frames by gender
# player_gender = gender(player_stats$First) %>% pull(gender)

scorecards = read_csv('scorecards.csv')
processed_stats = read_csv('processed_stats.csv')
```